---
# 'True' if environment uses Kerberos
kerberos_used: False

# 'True' if environment uses Kerberos
kubernetes_used: False

# access information for jumpbox
jumpbox:
 # ip address or hostname
 hostname: localhost
 # port for ssh connection (default 22)
 hostport: 22
 # username for ssh connection (default: ubuntu)
 username: ubuntu
 # absolute path to ssh key
 key_filename:
 # password to ssh key if key is encrypted
 key_password:

# cdh-manager configuration
cdh-manager:
 user: admin
 password: admin
 cm_port: 7180
 ssh_user: ec2-user

# environment name
envname: trustedanalytics

# count of 'worker' nodes
workers_count: 3

# count of 'master' nodes
masters_count: 3

# absolute paths
paths:
 cf_tiny_yml: /root/cf.yml
 ansible_hosts: /etc/ansible/hosts
 passwords_store: /root/apployer_passwords/

